apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: LoadBalancer
  selector:
    app: aggregator
  ports:
  - port: 8080
    targetPort: 80
    name: http
    protocol: TCP
